version: 2
updates:

  # Maintain dependencies for Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for mkdocs
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
